In [2]:
import numpy as np

In [3]:
a1 = np.array([[1, 2, 3, 3, 1],
               [ 6, 8, 11, 10, 7]])
a = a1.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

In [5]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [6]:
X1 = a_centered[:5, 0]
X1

array([-1.,  0.,  1.,  1., -1.])

In [7]:
X2 = a_centered[:5, 1:]
X2

array([[-2.4],
       [-0.4],
       [ 2.6],
       [ 1.6],
       [-1.4]])

In [8]:
a_centered_sp = a_centered[:5,0] @ a_centered[:5, 1]
a_centered_sp

8.0

In [9]:
z = np.array(a.shape)
z

array([5, 2])

In [10]:
answer = a_centered_sp/(z[0] - 1)
answer

2.0

In [11]:
covar = np.cov(a1)
covar

array([[1. , 2. ],
       [2. , 4.3]])