In [41]:
import numpy as np
import pandas as pd
import random

1.

In [5]:
a = np.arange(12, 24, 1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2 - 3

In [34]:
b1 = a[:4].reshape(2, 2)
b1


array([[12, 13],
       [14, 15]])

In [47]:
b2 = a[:9].reshape(3, 3)
b2


array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [43]:
b3 = a[5:11].reshape(3, 2)
b3

array([[17, 18],
       [19, 20],
       [21, 22]])

In [44]:
b4 = a[4:10].reshape(2, 3)
b4

array([[16, 17, 18],
       [19, 20, 21]])

In [46]:
b5 = a[:12].reshape(4, 3)
b5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [49]:
c1 = a[:4].reshape(2, -1)
c1

array([[12, 13],
       [14, 15]])

In [50]:
c2 = a[:9].reshape(3, -1)
c2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [51]:
c3 = a[4:10].reshape(2, -1)
c3

array([[16, 17, 18],
       [19, 20, 21]])

In [52]:
b4 = a[5:11].reshape(-1, 2)
b4

array([[17, 18],
       [19, 20],
       [21, 22]])

In [53]:
b5 = a[:12].reshape(-1, 3)
b5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [68]:
m = np.random.sample((3, 4)) - 0.5
m

array([[ 0.38333302,  0.26189184, -0.0105232 ,  0.3419616 ],
       [-0.11125874, -0.44398121, -0.30404413, -0.49400231],
       [ 0.08294583,  0.11210098, -0.479153  , -0.3138822 ]])

In [69]:
m1 = m.flatten()
m1

array([ 0.38333302,  0.26189184, -0.0105232 ,  0.3419616 , -0.11125874,
       -0.44398121, -0.30404413, -0.49400231,  0.08294583,  0.11210098,
       -0.479153  , -0.3138822 ])

6.

In [70]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7.

In [4]:
bx = np.arange(20, 0, -2)
bx

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [9]:
b = bx.reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

8.

In [15]:
a = np.zeros((2, 2,))
a

array([[0., 0.],
       [0., 0.]])

In [16]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
c = np.vstack((a, b))
c

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
c.size

10

9.

In [21]:
a = np.arange(1, 13, 1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
A = a.reshape(4, 3)
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [24]:
At = A.transpose()
At

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [25]:
B = np.dot(A, At)
B

array([[ 14,  32,  50,  68],
       [ 32,  77, 122, 167],
       [ 50, 122, 194, 266],
       [ 68, 167, 266, 365]])

10.

In [34]:
np.random.seed(42)

11.

In [35]:
m1 = np.arange(0, 16, 1)
m1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [54]:
np.random.shuffle(m1)
print(m1)

[ 5 14  1  3  4  9 13 15 10 11  6  8  0  7 12  2]
